msgtimer: 1
messages:
  - "&a-------------------------------\n &b1 \n &a-------------------------------"
  - "&a-------------------------------\n &b2 \n &a-------------------------------"
  - "&a-------------------------------\n &b3 \n &a-------------------------------"